version: "3.9"

services:
  db:
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  # frontend:
  #   build:
  #     context: ../frontend
  #     dockerfile: ../docker/dockerfile.frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ../frontend:/usr/app

  # backend:
  #   build:
  #     context: ../backend
  #     dockerfile: ../docker/dockerfile.backend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ../backend:/usr/app

volumes:
  db:
